### ISSUE TITLE
Antorus - Varimathras

### ISSUE THREAD

**Issue by xyyxz** [BigWigsMods/BigWigs#395]
### What steps will reproduce the problem?  
1.  Antorus - Varimathras
2.  
3.  

### What version of BigWigs are you using? (Stating 'latest' is not useful)

v76

### Do you have an error log of what happened?

Ability: Misery

Not showing in timers, not even with Emph + Countdown checked.

**Comment by Justw8** [comment]
It's a debuff you recieve when you stand alone, there are no timers for it. We only give you a warning when you are "hit" to notify you that you were alone.
What is your expected behavior?

**Comment by xyyxz** [comment]
I'm thinking, I didnt see my partner tank get the debuff, so he got oneshotted because I have no idea when he's getting it.

Should i adress WeakAura for that function?

**Comment by naeshy** [comment]
I'd actually like to second this request.  It's not the Misery part that needs to be triggered off of, I'd say it's his Shadow Strike.  Since this ability causes Misery as a shadow damage source, it's the mechanic that requires the tanks to constantly taunt swap or leave their tank mate to die.  

The only indication currently is focus targeting your co-tank to watch for Misery or taunting when the purple Shadow Strike graphic happens.  You can watch Varimathras' energy and at 100 be ready to taunt, but you still must wait for him to deliver his goods.

Request BigWigs Alert on cast of "Shadow Strike"

**Comment by Justw8** [comment]
There already is a warning for Shadow Strike.

**Comment by naeshy** [comment]
KK, just logged in and I do see the alert for Shadow Strike but I'm almost certain it wasn't not working last night on Varimathras normal.  I'll check next time we fight him...

Thanks for the quick reply!

**Comment by Justw8** [comment]
That could be a bug with the normal mode version, it was working on heroic today. I will take a look!

**Comment by Justw8** [comment]
Let us know if there are still issues after these fixes!

**Comment by xyyxz** [comment]
Thanks for the quick answers

**Comment by babydollm** [comment]
"Shadow Strike" does not say who its cast on in normal is that right ?

**Comment by Justw8** [comment]
@babydollm that is correct.
