### ISSUE TITLE
[7.3.5] Sounds randomly get chopped up or don't play

### ISSUE THREAD

**Issue by Polarthief** [BigWigsMods/BigWigs#424]
By far the worst on Imonar, but since the patch (7.3.5), on nearly every boss, the sounds get chopped or don't play at all. By "chopped up" I mean it will play the beginning of the sound, then not continue, or start up again towards the end of the sound, or again, just not even play to begin with.

It's also not all of them, but it's usually all of them on Aggramar for some reason.

**Comment by elvador** [comment]
As we were told by Blizzard, the sound channel priorities unintentionally changed. We will probably not implement any solution to this temporary problem, since it's going to be fixed soon™.

It might help addon sounds if you disable all sound sources in the WoW settings (System -> Sound -> Playback category). Keep in mind that you'll have to change that back to your preference when the bug is fixed.

A different workaround which might help is manually changing the BigWigs files to output sounds on the `"Dialog"` instead of the `"Master"` channel. Note that this will be overwritten if you update BigWigs.

![image](https://user-images.githubusercontent.com/8883045/35286627-d270ea00-0060-11e8-84c1-b3da53020e7e.png)

I'll leave this open for visibility, although I hope that it'll be fixed soon.

**Comment by Polarthief** [comment]
If it'll eventually just be fixed by Blizzard (hopefully soon!) that's good enough for me. Just wanted to make sure all that can be done is going to be whether this was on Blizzard's or BigWig's side. I figured this was a Blizzard thing (I mean, what WASN'T in 7.3.5? lol), but I had no idea what was going on behind the scenes so being left in the dark about your most important raid addon is a bit scary, especially when you don't realize how much you rely on those sounds for certain things

Thanks for the detailed answer (and workaround I'll probably get to sometime this week), glad to hear it'll be fixed on its own.

**Comment by nebularg** [comment]
You can also increase the number of sound channels the game uses to the max allowed by editing your WTF/Config.wtf and adding `SET Sound_NumChannels "128"` (Thanks Sehra on Discord)

**Comment by Polarthief** [comment]
Good to know, thanks! I'll probably do that as well.

Just had my first raid with the change and it went really well, until I realized WeakAuras was also affected and it felt even worse (just got done fixing that too, hopefully).

Thanks again for the workaround, Elvador. Really hope Soon™ is sooner than we think.

**Comment by elvador** [comment]
> ## Hotfixes: January 31
> ### Sounds
> - Fixed a bug that was preventing some addon sounds from playing correctly.
(via: https://worldofwarcraft.com/en-us/news/21365424)

Make sure to revert the workarounds and let us know if you still encounter any problems.

**Comment by Polarthief** [comment]
Thank you for the reminder! I actually missed that in the hotfixes so that would have been really annoying. Dialog was a PITA from time to time, so not used to having random things shouting at me during raid. (... well besides the raid leader)
