### ISSUE TITLE
Sludgefist Chain Link say symbols

### ISSUE THREAD

**Issue by CaleG** [BigWigsMods/BigWigs#877]
Is it possible to add /say with symbols to match the DBM functionality for Sludgefist?

**Comment by Justw8** [comment]
Possible, yes, but highly adviced against. 
The blizzard visual is really good and the say messages only make it harder to find your partners. 
Especially in Mythic, where the whole raid will recieve chains it becomes a say messages fiesta that is filling your screen. 

in DBM this functionality is turned off by default since a recent update, and I would suggest turning it off and trying it without.

**Comment by CaleGlisson** [comment]
Yeah I just noticed that default changed tonight, and things actually were better without it so there’s no real need for this. 

Thanks for the fast response! Feel free to close 👍
