### ISSUE TITLE
Issue with Stone Legion Generals timings.

### ISSUE THREAD

**Issue by Yaboitheos** [BigWigsMods/BigWigs#893]
## Describe the problem
As soon as first 50% intermission finishes, and General Grashaal becomes active, The first two timers of Wicked Blade and Reverberating Eruption are swapped. Causing all timers after this to be out of sync. Not entirely sure if swapping them will fix the entire timers. But every timer is out, future Wicked Blades, Reverberating Eruption, Seismic Upheaval, Crystalize etc.

### What steps will reproduce the problem?

1.  Heroic difficulty on Stone Legion Generals. First 50% intermission finishes and the first two timers are swapped. (Wicked Blade and Reverberating Eruption). Consistent with every pull.

### What version of BigWigs are you using? (Stating 'latest' is not useful)
During last nights raid v197

### Do you have an error log of what happened?
No error log

**Comment by Justw8** [comment]
Wicked Blade timers do not reset when you change stage, unless you time it so that it gets skipped/interrupted possibly. Eruption does have a cooldown after leaving the intermission. It's all a bit weird and timings change pull-pull depending on what the bosses did before. 
Improvements will be added soon.
