### ISSUE TITLE
Say option for Hungering Destroyer uses wrong raid icon

### ISSUE THREAD

**Issue by wheatbread** [BigWigsMods/BigWigs#988]
## Describe the problem
We are using a weak aura that marks people with miasma based on ERT notes groups with icons.  All boss mod options to auto mark are turned off, so that it’s only the weak aura doing the marking.  

When we get the miasma, bigwigs calls out the wrong icon in say when saying ‘miasma on me’.  It is an icon entirely different from the icon on the character’s head.  

Maybe an option for a split second delay in the say so that it can pull from the icon placed on us instead of presumably the icon it wants to auto use?

### What steps will reproduce the problem?

1.  
2.  
3.

**Comment by funkydude** [comment]
Even if we implement a delay (which I personally don't think is a good idea) there will never be that "correct" amount of delay to have. And then what, do you fall back to the original marker, potentially printing something wrong/conflicting with other markers, or do you print a blank marker, potentially messing it up for the majority that use standard marking?

The only solution I see to this is if someone wants to implement improved marking in BigWigs itself. Since the majority won't care how the marking is done, as long as the same marks are used.

**Comment by Justw8** [comment]
Or if it's really annoying, you can turn off the 'say' for Miasma, and leave on the repeating say messages for health which do check what icon you are marked with.
